"""Thin HTTP client for the ZATCA onboarding REST API (ORDS/APEX, engine-api/v1).

Unlike the old zatca.zainzone.net engine, this API is stateful: CCSID/PCSID
credentials and the private key are generated by the underlying FastAPI engine
and persisted server-side in Oracle (keyed by stamp_id, table DIGITAL_STAMPS)
by pkg_zatca_onboarding. /signup registers the company once and issues the API
key that authenticates every call after it; every onboarding call after
/onboarding/prepare is addressed by the stamp_id path segment that call
returns.

/onboarding/{stamp_id}/credentials is a one-time read of that Oracle-side
private key + PCSID for a unit that already has a Production CSID - called
exactly once right after /request-pcsid or /renew-pcsid succeeds, so the
ERPNext side can cache them (on ZATCA EGS Unit) instead of calling the engine
again for every invoice signed.

/cities is a public lookup (no API-KEY, backed by table ZATCA_CITIES) used to
populate ZATCA City - it's callable before Sign Up, since a company has to
pick its city_id as part of registering in the first place.
"""

import requests

ENGINE_BASE_URL = "https://hwpkkuu6mncvvf7-zain.adb.me-jeddah-1.oraclecloudapps.com/ords/zainzone/engine-api/v1"
"""Fixed - this is ZainZone's own ORDS instance, not something a company using
this app should ever need to point elsewhere, so it isn't exposed as a field
on ZATCA Settings."""


class ZatcaEngineError(Exception):
	"""Raised when the API reports failure - by HTTP status or by success: false in the body."""


class ZatcaEngineClient:
	def __init__(self, api_key: str | None = None, timeout: int = 30):
		self.base_url = ENGINE_BASE_URL
		self.api_key = api_key
		self.timeout = timeout

	def signup(self, payload: dict) -> dict:
		"""Register the subscriber and obtain their API key.

		Unauthenticated - the API key doesn't exist yet, this call is what
		creates it."""
		return self._post("/signup", payload, authed=False)

	def prepare_onboarding(self, otp: str, environment: str) -> dict:
		return self._post("/onboarding/prepare", {"otp": otp, "environment": environment})

	def compliance_checks(self, stamp_id) -> dict:
		return self._post(f"/onboarding/{stamp_id}/compliance-checks", {})

	def request_pcsid(self, stamp_id) -> dict:
		return self._post(f"/onboarding/{stamp_id}/request-pcsid", {})

	def renew_pcsid(self, stamp_id, otp: str) -> dict:
		return self._post(f"/onboarding/{stamp_id}/renew-pcsid", {"otp": otp})

	def get_credentials(self, stamp_id) -> dict:
		"""One-time fetch of the private key + PCSID (with its secret) for a
		unit that already has a Production CSID. Meant to be called exactly
		once per issuance/renewal, not per invoice."""
		return self._get(f"/onboarding/{stamp_id}/credentials")

	def list_cities(self, country: str = "SA") -> dict:
		"""Public lookup, no API key needed - callable before Sign Up."""
		return self._get("/cities", params={"country": country}, authed=False)

	def _post(self, path: str, payload: dict, authed: bool = True) -> dict:
		return self._request("POST", path, payload=payload, authed=authed)

	def _get(self, path: str, params: dict | None = None, authed: bool = True) -> dict:
		return self._request("GET", path, params=params, authed=authed)

	def _request(
		self,
		method: str,
		path: str,
		payload: dict | None = None,
		params: dict | None = None,
		authed: bool = True,
	) -> dict:
		headers = {}
		if authed:
			if not self.api_key:
				raise ZatcaEngineError("No API key on ZATCA Settings - run Sign Up first.")
			headers["API-KEY"] = self.api_key

		try:
			response = requests.request(
				method,
				f"{self.base_url}{path}",
				json=payload,
				params=params,
				headers=headers,
				timeout=self.timeout,
			)
		except requests.RequestException as e:
			raise ZatcaEngineError(f"Could not reach ZATCA onboarding API at {self.base_url}: {e}")

		return self._parse(response)

	def _parse(self, response: requests.Response) -> dict:
		try:
			body = response.json()
		except ValueError:
			body = None

		if not response.ok:
			raise ZatcaEngineError(self._error_message(body, response.status_code))

		# The ORDS layer returns 200 with a {"success": false, ...} body for
		# business-logic failures (e.g. compliance checks that didn't pass) -
		# only auth failures (401/403) use a non-2xx status.
		if isinstance(body, dict) and body.get("success") is False:
			raise ZatcaEngineError(self._error_message(body, response.status_code))

		return body or {}

	def _error_message(self, body, status_code: int) -> str:
		if not isinstance(body, dict):
			return f"ZATCA onboarding API returned HTTP {status_code}"

		message = body.get("message")
		if not isinstance(message, str) or not message:
			return f"ZATCA onboarding API returned HTTP {status_code}"

		code = body.get("code")
		return f"{code}: {message}" if code else message
